//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orphelinat.Service.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrphelinatEntities : DbContext
    {
        public OrphelinatEntities()
            : base("name=OrphelinatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateurs { get; set; }
        public virtual DbSet<Besoin> Besoins { get; set; }
        public virtual DbSet<Donateur> Donateurs { get; set; }
        public virtual DbSet<Evenement> Evenements { get; set; }
        public virtual DbSet<Orphelinat> Orphelinats { get; set; }
    }
}
